### PR TITLE
Swift 3 migration.

### PR DESCRIPTION
**Pull request by vadymmarkov**
@zenangst @RamonGilabert @onmyway133 
I'm planning to release a version with Swift 2 before we merge this.

### CODE REVIEW

**Comment by zenangst** [comment]
💃

**Comment by vadymmarkov** [comment]
@zenangst Travis is failing...

**Comment by RamonGilabert** [comment]
Still one check failing!

**Comment by zenangst** [comment]
wat?

screen shot 2016-10-11 at 07 33 47

**Comment by vadymmarkov** [comment]
@zenangst @RamonGilabert @onmyway133 Everything is migrated to Swift 3, including demos and README, so it's ready to be merged.

**Comment by zenangst** [comment]
🚀

**Pull request merged**
